server:
  port: 8080
  servlet:
    context-path: /iam

spring:
  application:
    name: iam-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iam?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: <<username>>
    password: <<password>>
  flyway:
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 18000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
