version: "3"
services:
  middleware-mysql:
    container_name: middleware-mysql
    image: mysql/mysql-server:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    networks:
      - middleware-networks
    volumes:
      - /data/infrastructure/middleware/mysql
  middleware-redis:
    container_name: middleware-redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - middleware-networks
  middleware-kafka:
    container_name: middleware-kafka
    image: per495/kafka:3.1.0
    ports:
      - 9092:9092
    restart: on-failure
    healthcheck:
      test: bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint:
      - sh
      - -c
      - |
        uuid=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${uuid} -c config/kraft/server.properties
        bin/kafka-server-start.sh config/kraft/server.properties
    networks:
      - middleware-networks
networks:
  middleware-networks:
    driver: bridge
