version: "3"
services:
  service-governance-consul:
    container_name: service-governance-consul
    image: consul:1.13.1
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - service-governance-networks
  service-governance-vault:
    container_name: service-governance-vault
    image: vault:1.9.1
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS:
    networks:
      - service-governance-networks
  service-governance-gateway:
    container_name: service-governance-gateway
    image: springcloud/spring-cloud-gateway:2.2.6.RELEASE
    ports:
      - 8080:8080
    networks:
      - service-governance-networks
networks:
  service-governance-networks:
    driver: bridge
