version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - /data/local-stack/mysql:/var/lib/mysql
    restart: "unless-stopped"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - /data/local-stack/postgres:/var/lib/postgresql/data
    restart: "unless-stopped"
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: "unless-stopped"
  kafka:
    container_name: kafka
    image: apache/kafka:3.9.0
    ports:
      - 9092:9092
    volumes:
      - /data/local-stack/kafka:/var/lib/kafka/data
    restart: "unless-stopped"
  consul:
    container_name: consul
    image: hashicorp/consul
    ports:
      - 8500:8500
      - 8600:8600
    environment:
      CONSUL_BIND_INTERFACE: eth0
    restart: "unless-stopped"
  vault:
    container_name: vault
    image: hashicorp/vault
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    volumes:
      - /data/local-stack/vault/config:/vault/config.d
    restart: "unless-stopped"
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - "/data/local-stack/minio/data:/data"
    command: server /data --console-address ":9001"
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - /data/local-stack/nexus/nexus-data:/nexus-data
    depends_on:
      - minio
    restart: "unless-stopped"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 38080:8080
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    command: start-dev
    depends_on:
      - mysql
    restart: "unless-stopped"
  neko:
    image: "m1k1o/neko:chromium"
    container_name: neko
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8083:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.31.124
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - "7575:7575"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/local-stack/homarr/configs:/app/data/configs
      - /data/local-stack/homarr/data:/data
      - /data/local-stack/homarr/icons:/app/public/icons
    restart: unless-stopped