apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8500
        args:
          - "agent"
          - "-bootstrap-expect=1"
          - "-server=true"
          - "-ui=true"
          - "-bind=127.0.0.1"