name: Publish package to GitHub Packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: github
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF
      - name: Publish package
        working-directory: ./common
        run: mvn --batch-mode deploy
        env:
          GITHUB_USER_REF: ${{ github.actor }}
          GITHUB_TOKEN_REF: ${{ secrets.PACKAGES_TOKEN }}